name: Despliegue en Fly.io

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Desplegar aplicación
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Validar archivo fly.toml
        run: cat fly/develop.toml

      - name: Desplegar en Fly.io
        run: flyctl deploy --remote-only -a chatsappai-develop
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
